
Currently Loaded Modules:
  1) tools/miniconda/python3.8/4.9.2

 

WARNING: overwriting environment variables set in the machine
overwriting variable nnUNet_raw_data_base nnUNet_preprocessed RESULTS_FOLDER OUTPUT
  Running command git clone -q https://github.com/FabianIsensee/hiddenlayer.git /tmp/pip-install-dtbfeis4/hiddenlayer_01d2c8c0087e45568664704fad94ae19
  Running command git checkout -b more_plotted_details --track origin/more_plotted_details
  Switched to a new branch 'more_plotted_details'
  Branch 'more_plotted_details' set up to track remote branch 'more_plotted_details' from 'origin'.
/var/spool/slurmd/job10533429/slurm_script: line 54: 1096483 Killed                  nnUNet_train 3d_fullres nnUNetTrainerV2 535 0 -c
/var/spool/slurmd/job10533429/slurm_script: line 55: 1405236 Killed                  nnUNet_train 3d_fullres nnUNetTrainerV2 535 1 -c
Traceback (most recent call last):
  File "/home/smaijer/.conda/envs/nn/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/smaijer/nnUNet/nnunet/run/run_training.py", line 172, in main
    trainer.load_latest_checkpoint()
  File "/home/smaijer/nnUNet/nnunet/training/network_training/network_trainer.py", line 309, in load_latest_checkpoint
    raise RuntimeError("No checkpoint found")
RuntimeError: No checkpoint found
Traceback (most recent call last):
  File "/home/smaijer/.conda/envs/nn/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/smaijer/nnUNet/nnunet/run/run_training.py", line 172, in main
    trainer.load_latest_checkpoint()
  File "/home/smaijer/nnUNet/nnunet/training/network_training/network_trainer.py", line 309, in load_latest_checkpoint
    raise RuntimeError("No checkpoint found")
RuntimeError: No checkpoint found
Traceback (most recent call last):
  File "/home/smaijer/.conda/envs/nn/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/smaijer/nnUNet/nnunet/run/run_training.py", line 172, in main
    trainer.load_latest_checkpoint()
  File "/home/smaijer/nnUNet/nnunet/training/network_training/network_trainer.py", line 309, in load_latest_checkpoint
    raise RuntimeError("No checkpoint found")
RuntimeError: No checkpoint found
Traceback (most recent call last):
  File "/home/smaijer/.conda/envs/nn/bin/nnUNet_determine_postprocessing", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_determine_postprocessing')())
  File "/home/smaijer/nnUNet/nnunet/postprocessing/consolidate_postprocessing_simple.py", line 56, in main
    consolidate_folds(folder, val)
  File "/home/smaijer/nnUNet/nnunet/postprocessing/consolidate_postprocessing.py", line 61, in consolidate_folds
    collect_cv_niftis(output_folder_base, output_folder_raw, validation_folder_name,
  File "/home/smaijer/nnUNet/nnunet/postprocessing/consolidate_postprocessing.py", line 31, in collect_cv_niftis
    raise RuntimeError("some folds are missing. Please run the full 5-fold cross-validation. "
RuntimeError: some folds are missing. Please run the full 5-fold cross-validation. The following folds seem to be missing: [2, 3, 4]
Traceback (most recent call last):
  File "/home/smaijer/.conda/envs/nn/bin/nnUNet_predict", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_predict')())
  File "/home/smaijer/nnUNet/nnunet/inference/predict_simple.py", line 217, in main
    predict_from_folder(model_folder_name, input_folder, output_folder, folds, save_npz, num_threads_preprocessing,
  File "/home/smaijer/nnUNet/nnunet/inference/predict.py", line 658, in predict_from_folder
    return predict_cases(model, list_of_lists[part_id::num_parts], output_files[part_id::num_parts], folds,
  File "/home/smaijer/nnUNet/nnunet/inference/predict.py", line 184, in predict_cases
    trainer, params = load_model_and_checkpoint_files(model, folds, mixed_precision=mixed_precision,
  File "/home/smaijer/nnUNet/nnunet/training/model_restore.py", line 147, in load_model_and_checkpoint_files
    all_params = [torch.load(i, map_location=torch.device('cpu')) for i in all_best_model_files]
  File "/home/smaijer/nnUNet/nnunet/training/model_restore.py", line 147, in <listcomp>
    all_params = [torch.load(i, map_location=torch.device('cpu')) for i in all_best_model_files]
  File "/home/smaijer/.conda/envs/nn/lib/python3.9/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/smaijer/.conda/envs/nn/lib/python3.9/site-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/smaijer/.conda/envs/nn/lib/python3.9/site-packages/torch/serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/exports/lkeb-hpc/smaijer/results/nnUNet/3d_fullres/Task535/nnUNetTrainerV2__nnUNetPlansv2.1/fold_2/model_final_checkpoint.model'
Traceback (most recent call last):
  File "/home/smaijer/.conda/envs/nn/bin/nnUNet_predict", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_predict')())
  File "/home/smaijer/nnUNet/nnunet/inference/predict_simple.py", line 217, in main
    predict_from_folder(model_folder_name, input_folder, output_folder, folds, save_npz, num_threads_preprocessing,
  File "/home/smaijer/nnUNet/nnunet/inference/predict.py", line 636, in predict_from_folder
    case_ids = check_input_folder_and_return_caseIDs(input_folder, expected_num_modalities)
  File "/home/smaijer/nnUNet/nnunet/inference/predict.py", line 577, in check_input_folder_and_return_caseIDs
    assert len(files) > 0, "input folder did not contain any images (expected to find .nii.gz file endings)"
AssertionError: input folder did not contain any images (expected to find .nii.gz file endings)
Traceback (most recent call last):
  File "/home/smaijer/.conda/envs/nn/bin/nnUNet_evaluate_folder", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_evaluate_folder')())
  File "/home/smaijer/nnUNet/nnunet/evaluation/evaluator.py", line 483, in nnunet_evaluate_folder
    return evaluate_folder(args.ref, args.pred, args.l)
  File "/home/smaijer/nnUNet/nnunet/evaluation/evaluator.py", line 456, in evaluate_folder
    assert all([i in files_pred for i in files_gt]), "files missing in folder_with_predictions"
AssertionError: files missing in folder_with_predictions
OrderedDict([('all', []), ('mean', OrderedDict())])
slurmstepd: error: Detected 44 oom-kill event(s) in StepId=10533429.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
