environment: /usr/share/lmod/lmod/libexec/lmod: No such file or directory
environment: /usr/share/lmod/lmod/libexec/lmod: No such file or directory
environment: /usr/share/lmod/lmod/libexec/lmod: No such file or directory
/var/spool/slurmd/job10621850/slurm_script: line 38: conda: command not found
  Running command git clone -q https://github.com/FabianIsensee/hiddenlayer.git /tmp/pip-install-iyfwxsug/hiddenlayer_0d3261948b0e47d6b6a0b73c2e03acfb
  Running command git checkout -b more_plotted_details --track origin/more_plotted_details
  Switched to a new branch 'more_plotted_details'
  Branch 'more_plotted_details' set up to track remote branch 'more_plotted_details' from 'origin'.
WARNING: You are using pip version 21.2.4; however, version 22.1.2 is available.
You should consider upgrading via the '/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/bin/python -m pip install --upgrade pip' command.
WARNING: You are using pip version 21.2.4; however, version 22.1.2 is available.
You should consider upgrading via the '/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/bin/python -m pip install --upgrade pip' command.
/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/lib/python3.10/site-packages/torch/cuda/__init__.py:146: UserWarning: 
NVIDIA RTX A6000 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA RTX A6000 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Traceback (most recent call last):
  File "/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/smaijer/code/nnUNet/nnunet/run/run_training.py", line 172, in main
    trainer.load_latest_checkpoint()
  File "/home/smaijer/code/nnUNet/nnunet/training/network_training/network_trainer.py", line 304, in load_latest_checkpoint
    return self.load_checkpoint(join(self.output_folder, "model_final_checkpoint.model"), train=train)
  File "/home/smaijer/code/nnUNet/nnunet/training/network_training/network_trainer.py", line 323, in load_checkpoint
    self.load_checkpoint_ram(saved_model, train)
  File "/home/smaijer/code/nnUNet/nnunet/training/network_training/network_trainer.py", line 365, in load_checkpoint_ram
    self.amp_grad_scaler.load_state_dict(checkpoint['amp_grad_scaler'])
  File "/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 502, in load_state_dict
    raise RuntimeError("The source state dict is empty, possibly because it was saved "
RuntimeError: The source state dict is empty, possibly because it was saved from a disabled instance of GradScaler.
