
Currently Loaded Modules:
  1) tools/miniconda/python3.8/4.9.2

 

WARNING: overwriting environment variables set in the machine
overwriting variable nnUNet_raw_data_base nnUNet_preprocessed RESULTS_FOLDER OUTPUT
  Running command git clone -q https://github.com/FabianIsensee/hiddenlayer.git /tmp/pip-install-hplvl577/hiddenlayer_df9904e9a6c845779d3237720d77c41a
  Running command git checkout -b more_plotted_details --track origin/more_plotted_details
  Switched to a new branch 'more_plotted_details'
  Branch 'more_plotted_details' set up to track remote branch 'more_plotted_details' from 'origin'.
ERROR: Exception:
Traceback (most recent call last):
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
    status = self.run(options, args)
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 446, in run
    self._handle_target_dir(
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 501, in _handle_target_dir
    shutil.rmtree(target_item_dir)
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/shutil.py", line 732, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/shutil.py", line 671, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/shutil.py", line 669, in _rmtree_safe_fd
    os.rmdir(entry.name, dir_fd=topfd)
OSError: [Errno 39] Directory not empty: 'lib'
Traceback (most recent call last):
  File "/exports/lkeb-hpc/smaijer/envs/nn/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet==1.7.0', 'console_scripts', 'nnUNet_train')())
  File "/exports/lkeb-hpc/smaijer/envs/nn/bin/nnUNet_train", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/nnunet-1.7.0-py3.9.egg/nnunet/run/run_training.py", line 18, in <module>
    from nnunet.run.default_configuration import get_default_configuration
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/nnunet-1.7.0-py3.9.egg/nnunet/run/default_configuration.py", line 20, in <module>
    from nnunet.training.model_restore import recursive_find_python_class
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/nnunet-1.7.0-py3.9.egg/nnunet/training/model_restore.py", line 16, in <module>
    import torch
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/torch/__init__.py", line 198, in <module>
    _load_global_deps()
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/torch/__init__.py", line 151, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/torch/lib/libtorch_global_deps.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/exports/lkeb-hpc/smaijer/envs/nn/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet==1.7.0', 'console_scripts', 'nnUNet_train')())
  File "/exports/lkeb-hpc/smaijer/envs/nn/bin/nnUNet_train", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/nnunet-1.7.0-py3.9.egg/nnunet/run/run_training.py", line 18, in <module>
    from nnunet.run.default_configuration import get_default_configuration
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/nnunet-1.7.0-py3.9.egg/nnunet/run/default_configuration.py", line 20, in <module>
    from nnunet.training.model_restore import recursive_find_python_class
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/nnunet-1.7.0-py3.9.egg/nnunet/training/model_restore.py", line 16, in <module>
    import torch
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/torch/__init__.py", line 198, in <module>
    _load_global_deps()
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/torch/__init__.py", line 151, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/torch/lib/libtorch_global_deps.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/exports/lkeb-hpc/smaijer/envs/nn/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet==1.7.0', 'console_scripts', 'nnUNet_train')())
  File "/exports/lkeb-hpc/smaijer/envs/nn/bin/nnUNet_train", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/nnunet-1.7.0-py3.9.egg/nnunet/run/run_training.py", line 18, in <module>
    from nnunet.run.default_configuration import get_default_configuration
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/nnunet-1.7.0-py3.9.egg/nnunet/run/default_configuration.py", line 20, in <module>
    from nnunet.training.model_restore import recursive_find_python_class
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/nnunet-1.7.0-py3.9.egg/nnunet/training/model_restore.py", line 16, in <module>
    import torch
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/torch/__init__.py", line 198, in <module>
    _load_global_deps()
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/torch/__init__.py", line 151, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/torch/lib/libtorch_global_deps.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/exports/lkeb-hpc/smaijer/envs/nn/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet==1.7.0', 'console_scripts', 'nnUNet_train')())
  File "/exports/lkeb-hpc/smaijer/envs/nn/bin/nnUNet_train", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/nnunet-1.7.0-py3.9.egg/nnunet/run/run_training.py", line 18, in <module>
    from nnunet.run.default_configuration import get_default_configuration
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/nnunet-1.7.0-py3.9.egg/nnunet/run/default_configuration.py", line 20, in <module>
    from nnunet.training.model_restore import recursive_find_python_class
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/nnunet-1.7.0-py3.9.egg/nnunet/training/model_restore.py", line 16, in <module>
    import torch
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/torch/__init__.py", line 198, in <module>
    _load_global_deps()
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/torch/__init__.py", line 151, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/torch/lib/libtorch_global_deps.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/exports/lkeb-hpc/smaijer/envs/nn/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet==1.7.0', 'console_scripts', 'nnUNet_train')())
  File "/exports/lkeb-hpc/smaijer/envs/nn/bin/nnUNet_train", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/nnunet-1.7.0-py3.9.egg/nnunet/run/run_training.py", line 18, in <module>
    from nnunet.run.default_configuration import get_default_configuration
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/nnunet-1.7.0-py3.9.egg/nnunet/run/default_configuration.py", line 20, in <module>
    from nnunet.training.model_restore import recursive_find_python_class
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/nnunet-1.7.0-py3.9.egg/nnunet/training/model_restore.py", line 16, in <module>
    import torch
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/torch/__init__.py", line 198, in <module>
    _load_global_deps()
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/torch/__init__.py", line 151, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/torch/lib/libtorch_global_deps.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/exports/lkeb-hpc/smaijer/envs/nn/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet==1.7.0', 'console_scripts', 'nnUNet_train')())
  File "/exports/lkeb-hpc/smaijer/envs/nn/bin/nnUNet_train", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/nnunet-1.7.0-py3.9.egg/nnunet/run/run_training.py", line 18, in <module>
    from nnunet.run.default_configuration import get_default_configuration
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/nnunet-1.7.0-py3.9.egg/nnunet/run/default_configuration.py", line 20, in <module>
    from nnunet.training.model_restore import recursive_find_python_class
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/nnunet-1.7.0-py3.9.egg/nnunet/training/model_restore.py", line 16, in <module>
    import torch
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/torch/__init__.py", line 198, in <module>
    _load_global_deps()
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/torch/__init__.py", line 151, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/torch/lib/libtorch_global_deps.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/exports/lkeb-hpc/smaijer/envs/nn/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet==1.7.0', 'console_scripts', 'nnUNet_train')())
  File "/exports/lkeb-hpc/smaijer/envs/nn/bin/nnUNet_train", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/nnunet-1.7.0-py3.9.egg/nnunet/run/run_training.py", line 18, in <module>
    from nnunet.run.default_configuration import get_default_configuration
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/nnunet-1.7.0-py3.9.egg/nnunet/run/default_configuration.py", line 20, in <module>
    from nnunet.training.model_restore import recursive_find_python_class
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/nnunet-1.7.0-py3.9.egg/nnunet/training/model_restore.py", line 16, in <module>
    import torch
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/torch/__init__.py", line 198, in <module>
    _load_global_deps()
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/torch/__init__.py", line 151, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/torch/lib/libtorch_global_deps.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/exports/lkeb-hpc/smaijer/envs/nn/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet==1.7.0', 'console_scripts', 'nnUNet_train')())
  File "/exports/lkeb-hpc/smaijer/envs/nn/bin/nnUNet_train", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/nnunet-1.7.0-py3.9.egg/nnunet/run/run_training.py", line 18, in <module>
    from nnunet.run.default_configuration import get_default_configuration
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/nnunet-1.7.0-py3.9.egg/nnunet/run/default_configuration.py", line 20, in <module>
    from nnunet.training.model_restore import recursive_find_python_class
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/nnunet-1.7.0-py3.9.egg/nnunet/training/model_restore.py", line 16, in <module>
    import torch
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/torch/__init__.py", line 198, in <module>
    _load_global_deps()
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/torch/__init__.py", line 151, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/torch/lib/libtorch_global_deps.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/exports/lkeb-hpc/smaijer/envs/nn/bin/nnUNet_determine_postprocessing", line 33, in <module>
    sys.exit(load_entry_point('nnunet==1.7.0', 'console_scripts', 'nnUNet_determine_postprocessing')())
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/nnunet-1.7.0-py3.9.egg/nnunet/postprocessing/consolidate_postprocessing_simple.py", line 56, in main
    consolidate_folds(folder, val)
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/nnunet-1.7.0-py3.9.egg/nnunet/postprocessing/consolidate_postprocessing.py", line 61, in consolidate_folds
    collect_cv_niftis(output_folder_base, output_folder_raw, validation_folder_name,
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/nnunet-1.7.0-py3.9.egg/nnunet/postprocessing/consolidate_postprocessing.py", line 31, in collect_cv_niftis
    raise RuntimeError("some folds are missing. Please run the full 5-fold cross-validation. "
RuntimeError: some folds are missing. Please run the full 5-fold cross-validation. The following folds seem to be missing: [2, 3, 4]
Traceback (most recent call last):
  File "/exports/lkeb-hpc/smaijer/envs/nn/bin/nnUNet_predict", line 33, in <module>
    sys.exit(load_entry_point('nnunet==1.7.0', 'console_scripts', 'nnUNet_predict')())
  File "/exports/lkeb-hpc/smaijer/envs/nn/bin/nnUNet_predict", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/nnunet-1.7.0-py3.9.egg/nnunet/inference/predict_simple.py", line 17, in <module>
    import torch
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/torch/__init__.py", line 198, in <module>
    _load_global_deps()
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/torch/__init__.py", line 151, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/torch/lib/libtorch_global_deps.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/exports/lkeb-hpc/smaijer/envs/nn/bin/nnUNet_predict", line 33, in <module>
    sys.exit(load_entry_point('nnunet==1.7.0', 'console_scripts', 'nnUNet_predict')())
  File "/exports/lkeb-hpc/smaijer/envs/nn/bin/nnUNet_predict", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/nnunet-1.7.0-py3.9.egg/nnunet/inference/predict_simple.py", line 17, in <module>
    import torch
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/torch/__init__.py", line 198, in <module>
    _load_global_deps()
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/torch/__init__.py", line 151, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/torch/lib/libtorch_global_deps.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/exports/lkeb-hpc/smaijer/envs/nn/bin/nnUNet_evaluate_folder", line 33, in <module>
    sys.exit(load_entry_point('nnunet==1.7.0', 'console_scripts', 'nnUNet_evaluate_folder')())
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/nnunet-1.7.0-py3.9.egg/nnunet/evaluation/evaluator.py", line 483, in nnunet_evaluate_folder
    return evaluate_folder(args.ref, args.pred, args.l)
  File "/exports/lkeb-hpc/smaijer/envs/nn/lib/python3.9/site-packages/nnunet-1.7.0-py3.9.egg/nnunet/evaluation/evaluator.py", line 456, in evaluate_folder
    assert all([i in files_pred for i in files_gt]), "files missing in folder_with_predictions"
AssertionError: files missing in folder_with_predictions
OrderedDict([('all', []), ('mean', OrderedDict())])
