
Currently Loaded Modules:
  1) system/python/3.10.2

 

/var/spool/slurmd/job12318555/slurm_script: line 38: conda: command not found
  Running command git clone -q https://github.com/FabianIsensee/hiddenlayer.git /tmp/pip-install-wval6rgd/hiddenlayer_e8fc239c274942229dc97d8e39c487ae
  Running command git checkout -b more_plotted_details --track origin/more_plotted_details
  Switched to a new branch 'more_plotted_details'
  Branch 'more_plotted_details' set up to track remote branch 'more_plotted_details' from 'origin'.
WARNING: You are using pip version 21.2.4; however, version 22.2.2 is available.
You should consider upgrading via the '/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/bin/python -m pip install --upgrade pip' command.
ERROR: ditable is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
WARNING: You are using pip version 21.2.4; however, version 22.2.2 is available.
You should consider upgrading via the '/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/bin/python -m pip install --upgrade pip' command.
/var/spool/slurmd/job12318555/slurm_script: line 45: [: ==: unary operator expected
Traceback (most recent call last):
  File "/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/smaijer/code/nnUNet/nnunet/run/run_training.py", line 175, in main
    load_pretrained_weights(trainer.network, args.pretrained_weights)
  File "/home/smaijer/code/nnUNet/nnunet/run/load_pretrained_weights.py", line 65, in load_pretrained_weights
    raise RuntimeError("Pretrained weights are not compatible with the current network architecture")
RuntimeError: Pretrained weights are not compatible with the current network architecture
Traceback (most recent call last):
  File "/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/smaijer/code/nnUNet/nnunet/run/run_training.py", line 175, in main
    load_pretrained_weights(trainer.network, args.pretrained_weights)
  File "/home/smaijer/code/nnUNet/nnunet/run/load_pretrained_weights.py", line 65, in load_pretrained_weights
    raise RuntimeError("Pretrained weights are not compatible with the current network architecture")
RuntimeError: Pretrained weights are not compatible with the current network architecture
Traceback (most recent call last):
  File "/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/smaijer/code/nnUNet/nnunet/run/run_training.py", line 175, in main
    load_pretrained_weights(trainer.network, args.pretrained_weights)
  File "/home/smaijer/code/nnUNet/nnunet/run/load_pretrained_weights.py", line 65, in load_pretrained_weights
    raise RuntimeError("Pretrained weights are not compatible with the current network architecture")
RuntimeError: Pretrained weights are not compatible with the current network architecture
Traceback (most recent call last):
  File "/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/smaijer/code/nnUNet/nnunet/run/run_training.py", line 175, in main
    load_pretrained_weights(trainer.network, args.pretrained_weights)
  File "/home/smaijer/code/nnUNet/nnunet/run/load_pretrained_weights.py", line 65, in load_pretrained_weights
    raise RuntimeError("Pretrained weights are not compatible with the current network architecture")
RuntimeError: Pretrained weights are not compatible with the current network architecture
Traceback (most recent call last):
  File "/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/smaijer/code/nnUNet/nnunet/run/run_training.py", line 175, in main
    load_pretrained_weights(trainer.network, args.pretrained_weights)
  File "/home/smaijer/code/nnUNet/nnunet/run/load_pretrained_weights.py", line 65, in load_pretrained_weights
    raise RuntimeError("Pretrained weights are not compatible with the current network architecture")
RuntimeError: Pretrained weights are not compatible with the current network architecture
Traceback (most recent call last):
  File "/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/smaijer/code/nnUNet/nnunet/run/run_training.py", line 172, in main
    trainer.load_latest_checkpoint()
  File "/home/smaijer/code/nnUNet/nnunet/training/network_training/network_trainer.py", line 309, in load_latest_checkpoint
    raise RuntimeError("No checkpoint found")
RuntimeError: No checkpoint found
Traceback (most recent call last):
  File "/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/smaijer/code/nnUNet/nnunet/run/run_training.py", line 172, in main
    trainer.load_latest_checkpoint()
  File "/home/smaijer/code/nnUNet/nnunet/training/network_training/network_trainer.py", line 309, in load_latest_checkpoint
    raise RuntimeError("No checkpoint found")
RuntimeError: No checkpoint found
Traceback (most recent call last):
  File "/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/smaijer/code/nnUNet/nnunet/run/run_training.py", line 172, in main
    trainer.load_latest_checkpoint()
  File "/home/smaijer/code/nnUNet/nnunet/training/network_training/network_trainer.py", line 309, in load_latest_checkpoint
    raise RuntimeError("No checkpoint found")
RuntimeError: No checkpoint found
Traceback (most recent call last):
  File "/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/smaijer/code/nnUNet/nnunet/run/run_training.py", line 172, in main
    trainer.load_latest_checkpoint()
  File "/home/smaijer/code/nnUNet/nnunet/training/network_training/network_trainer.py", line 309, in load_latest_checkpoint
    raise RuntimeError("No checkpoint found")
RuntimeError: No checkpoint found
Traceback (most recent call last):
  File "/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/smaijer/code/nnUNet/nnunet/run/run_training.py", line 172, in main
    trainer.load_latest_checkpoint()
  File "/home/smaijer/code/nnUNet/nnunet/training/network_training/network_trainer.py", line 309, in load_latest_checkpoint
    raise RuntimeError("No checkpoint found")
RuntimeError: No checkpoint found
Traceback (most recent call last):
  File "/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/bin/nnUNet_determine_postprocessing", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_determine_postprocessing')())
  File "/home/smaijer/code/nnUNet/nnunet/postprocessing/consolidate_postprocessing_simple.py", line 58, in main
    consolidate_folds(folder, val, folds=folds)
  File "/home/smaijer/code/nnUNet/nnunet/postprocessing/consolidate_postprocessing.py", line 61, in consolidate_folds
    collect_cv_niftis(output_folder_base, output_folder_raw, validation_folder_name,
  File "/home/smaijer/code/nnUNet/nnunet/postprocessing/consolidate_postprocessing.py", line 31, in collect_cv_niftis
    raise RuntimeError("some folds are missing. Please run the full 5-fold cross-validation. "
RuntimeError: some folds are missing. Please run the full 5-fold cross-validation. The following folds seem to be missing: [0, 1, 2, 3, 4]
Traceback (most recent call last):
  File "/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/bin/nnUNet_predict", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_predict')())
  File "/home/smaijer/code/nnUNet/nnunet/inference/predict_simple.py", line 217, in main
    predict_from_folder(model_folder_name, input_folder, output_folder, folds, save_npz, num_threads_preprocessing,
  File "/home/smaijer/code/nnUNet/nnunet/inference/predict.py", line 650, in predict_from_folder
    shutil.copy(join(model, 'plans.pkl'), output_folder)
  File "/share/software/system/python/3.10.2/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/share/software/system/python/3.10.2/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/exports/lkeb-hpc/smaijer/results/nnUNet/3d_fullres/Task601/nnUNetTrainerV2__nnUNetPlansv2.1/plans.pkl'
Traceback (most recent call last):
  File "/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/bin/nnUNet_predict", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_predict')())
  File "/home/smaijer/code/nnUNet/nnunet/inference/predict_simple.py", line 217, in main
    predict_from_folder(model_folder_name, input_folder, output_folder, folds, save_npz, num_threads_preprocessing,
  File "/home/smaijer/code/nnUNet/nnunet/inference/predict.py", line 650, in predict_from_folder
    shutil.copy(join(model, 'plans.pkl'), output_folder)
  File "/share/software/system/python/3.10.2/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/share/software/system/python/3.10.2/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/exports/lkeb-hpc/smaijer/results/nnUNet/3d_fullres/Task601/nnUNetTrainerV2__nnUNetPlansv2.1/plans.pkl'
Traceback (most recent call last):
  File "/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/bin/nnUNet_evaluate_folder", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_evaluate_folder')())
  File "/home/smaijer/code/nnUNet/nnunet/evaluation/evaluator.py", line 483, in nnunet_evaluate_folder
    return evaluate_folder(args.ref, args.pred, args.l)
  File "/home/smaijer/code/nnUNet/nnunet/evaluation/evaluator.py", line 456, in evaluate_folder
    assert all([i in files_pred for i in files_gt]), "files missing in folder_with_predictions"
AssertionError: files missing in folder_with_predictions
Traceback (most recent call last):
  File "/exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/bin/nnUNet_evaluate_folder", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_evaluate_folder')())
  File "/home/smaijer/code/nnUNet/nnunet/evaluation/evaluator.py", line 483, in nnunet_evaluate_folder
    return evaluate_folder(args.ref, args.pred, args.l)
  File "/home/smaijer/code/nnUNet/nnunet/evaluation/evaluator.py", line 456, in evaluate_folder
    assert all([i in files_pred for i in files_gt]), "files missing in folder_with_predictions"
AssertionError: files missing in folder_with_predictions
